M48
; DRILL file {KiCad 8.0.3} date 2025-12-30T10:32:46+1300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-30T10:32:46+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X155.0Y-92.1
X155.0Y-100.9
T2
X115.0Y-59.0
X115.0Y-133.0
X171.0Y-59.0
X171.0Y-133.0
M30
