M48
; DRILL file {KiCad 9.0.4} date 2026-01-25T12:04:24+1300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-25T12:04:24+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X126.607Y-117.109
X131.457Y-117.109
T2
X126.307Y-120.139
X131.757Y-120.139
T3
X83.101Y-96.139
M30
